server:
  port: 8090

spring:
  application:
    name: pg-ms-auth
  datasource:
    url: ${SUPABASE_URL_AUTH}
    username: ${SUPABASE_USER}
    password: ${SUPABASE_PASSWORD}

    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 30000
      pool-name: HikariPool-Auth
      data-source-properties:
        prepareThreshold: 0 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        prefer-ip-address: false
        instance-id: ${spring.application.name}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
    protocol: smtp
    default-encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-key: ${JWT_SECRET}
    token-expiration: 3600000
    reset-token-expiration-minutes: 10

microservicio:
  notificaciones:
    url: ${NOTIFICACIONES_SERVICE_URL:http://pg-ms-notifications:8083}
biometric:
  jwt:
    secret-key: ${BIOMETRIC_JWT_SECRET}
    token-expiration: 300000

logging:
  level:
    com.pulse_gym: DEBUG
    com.pulse_gym.ms_auth.services: DEBUG
    org.springframework.web: DEBUG